import Window from "./window";

// This allows TypeScript to use the magic constant that's auto-generated by Electron Forge's Webpack plugin.
declare const DOCS_WINDOW_WEBPACK_ENTRY: string;
declare const DOCS_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

class DocsWindow extends Window {
  constructor(darkMode: boolean, section: string) {
    super(
      DOCS_WINDOW_WEBPACK_ENTRY,
      DOCS_WINDOW_PRELOAD_WEBPACK_ENTRY,
      darkMode
    ); // TODO use builder design pattern?

    this.window.webContents.once("did-finish-load", () => {
      this.send("docs:jump", section);
    });
  }

  focus(section?: string) {
    if (section) this.send("docs:jump", section);

    this.window.focus();
  }
}

export default DocsWindow;
